In [1]:
import torch

In [2]:
# Создание заполненных тензоров
print(torch.zeros([3, 4]))
print(torch.ones([3, 4, 4]))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [3]:
# Размер тензора, сложение с константой, возведение в степень
x = torch.Tensor([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9, 10, 11, 12]])
print(x.size())
print(x.shape)
print(x[0, 2])
print(x + 10)
print(x ** 2)

torch.Size([3, 4])
torch.Size([3, 4])
tensor(3.)
tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])
tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])


In [4]:
# Операции между тензорами
y = torch.Tensor([[12, 11, 10, 9],
                  [8, 7, 6, 5],
                  [4, 3, 2, 1]])
print(x + y)
print(x * y)
print(x / y)
print(x % y)

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])
tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])
tensor([[ 0.0833,  0.1818,  0.3000,  0.4444],
        [ 0.6250,  0.8571,  1.1667,  1.6000],
        [ 2.2500,  3.3333,  5.5000, 12.0000]])
tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])


In [5]:
# Маленькие задачи для разминки
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])
print(a % b)
print(b[0] + a[2])

tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([2., 3., 4., 5.])


In [6]:
# Некоторые дополнительные математические функции
print(torch.exp(x))
print(torch.sin(x))
print(torch.log(x))

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])
tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])
tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])


In [9]:
# Тензор-маска, вывод элементов тензора через маску
mask = x > 3
print(mask)
print(x[mask])

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [10]:
# Реализуйте при помощи pyTorch функцию, которая возвращает сумму (x.sum()) элементов тензора X,
# строго превышающих значение limit, которое является входным значением алгоритма.
In = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = 5
LimitMask = In > limit
torch.sum(In[LimitMask])

tensor(30)

In [11]:
# Копирование по ссылке
y = x
y[0, 0] = 999
print(x, '\n', y)

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]]) 
 tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [12]:
# Полное копирование в памяти
x[0, 0] = 1
y = x.clone()
y[0, 0] = 999
print(x, '\n', y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]]) 
 tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [13]:
# Тип данных, хранящихся в тензорах, преобразование этого типа
print(x.dtype)
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

torch.float32
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [14]:
# Взаимодействие тензоров PyTorch с массивами NumPy
import numpy as np
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
print(x, '\n')
x = torch.from_numpy(x)
print(x, '\n')
x = x.numpy()
print(x)

[[1 2 3 4]
 [4 3 2 1]] 

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]]) 

[[1 2 3 4]
 [4 3 2 1]]


In [15]:
# Рандомный тензор
x = torch.rand([2000,3000])
print(x, '\n')

# Проверка, доступно ли устройство CUDA (видеокарта)
print(torch.cuda.is_available())

tensor([[0.4007, 0.2221, 0.4523,  ..., 0.0713, 0.2542, 0.8790],
        [0.5167, 0.5634, 0.2620,  ..., 0.9533, 0.1309, 0.0222],
        [0.3142, 0.2351, 0.6852,  ..., 0.2088, 0.4387, 0.2917],
        ...,
        [0.2592, 0.7810, 0.6453,  ..., 0.6850, 0.9671, 0.2938],
        [0.9881, 0.6599, 0.2464,  ..., 0.6632, 0.6142, 0.2708],
        [0.0464, 0.9981, 0.9294,  ..., 0.0777, 0.9405, 0.5788]]) 

True


In [16]:
# Выбор в качестве устройства выполнения первую видеокарту
torch.device('cuda:0')

device(type='cuda', index=0)

In [17]:
# Выбор в качестве устройства выполнения процессор
torch.device('cpu')

device(type='cpu')

In [18]:
# Универсальный код, выбирающий доступное устройство выполнения
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


In [19]:
# Копируем тензор в память CUDA устройства
x_cuda = x.to(device)
print(x_cuda, '\n')
# Замер времени выполнения на CPU
%time y = (x - x + x * 10.0) ** 2
# Замер времени выполнения на GPU
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

tensor([[0.4007, 0.2221, 0.4523,  ..., 0.0713, 0.2542, 0.8790],
        [0.5167, 0.5634, 0.2620,  ..., 0.9533, 0.1309, 0.0222],
        [0.3142, 0.2351, 0.6852,  ..., 0.2088, 0.4387, 0.2917],
        ...,
        [0.2592, 0.7810, 0.6453,  ..., 0.6850, 0.9671, 0.2938],
        [0.9881, 0.6599, 0.2464,  ..., 0.6632, 0.6142, 0.2708],
        [0.0464, 0.9981, 0.9294,  ..., 0.0777, 0.9405, 0.5788]],
       device='cuda:0') 

CPU times: user 20.5 ms, sys: 28.4 ms, total: 48.9 ms
Wall time: 47.4 ms
CPU times: user 487 µs, sys: 1.86 ms, total: 2.34 ms
Wall time: 3.44 ms
