# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

a = np.random.randint(0,20,size=(4,7))
a

array([[13,  0, 16, 15, 16,  4,  0],
       [ 6,  4, 11, 17,  4,  3, 17],
       [13, 19,  6,  1,  8, 18,  5],
       [ 0,  6, 17, 12,  2, 14,  0]])

In [2]:
a = np.random.uniform(0,20,size=(4, 7))
a

array([[ 7.79432542,  5.28288419,  3.39883119,  4.78948623,  6.38529524,
         5.85178988,  4.16408766],
       [ 9.79814383,  0.16184697,  4.20490815, 17.03746076,  0.5608315 ,
         6.27368809, 18.13063635],
       [10.04671942, 15.60790423,  4.56632572,  3.36204221,  0.54787138,
         2.20957082,  3.13576912],
       [ 2.37256427, 18.90456349, 18.08418961, 16.14434127,  5.94353243,
         0.21963504, 14.1431402 ]])

In [3]:
minn = a.min()
maxx = a.max()
print('max= ', maxx, 'mib= ', minn)

max=  18.904563490930673 mib=  0.1618469690344848


In [4]:
a_new = (a - minn) / (maxx - minn)
a_new

array([[0.4072237 , 0.27322812, 0.17270625, 0.24690334, 0.33204623,
        0.30358155, 0.21353579],
       [0.51413555, 0.        , 0.21571372, 0.90038249, 0.02128744,
        0.32609153, 0.95870785],
       [0.52739807, 0.82410985, 0.23499682, 0.17074341, 0.02059597,
        0.10925438, 0.15867082],
       [0.11795074, 1.        , 0.95622972, 0.85273094, 0.30847639,
        0.00308323, 0.74595874]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [5]:
b = np.random.randint(0,10,size=(8,10))


In [6]:
b.sum(axis=0).argmin()
print(b.sum(axis=0))
print(b.sum(axis=0).argmin())

[28 44 37 36 42 27 43 36 26 31]
8


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [7]:
a= np.array([5,5,5])
b=np.array([2,2,2])


r=(a-b)
print(r)
r2=(a-b)**2
print(r2)
sum2=r2.sum()
print(sum2)
d= sum2**.5
print(d)

d2=(((a-b)**2).sum())**0.5
print('d2= ',d2)

[3 3 3]
[9 9 9]
27
5.196152422706632
d2=  5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [9]:
dataset = np.loadtxt("data/minutes_n_ingredients.csv", dtype=int, delimiter=',', skiprows=1)
ids = dataset[:,0]
time = dataset[:, 1]
ingredients = dataset[:, 2]
print(dataset[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [10]:
import pandas as pd

pd_dataset = pd.read_csv("data/minutes_n_ingredients.csv")
pd_dataset[:5]

id  minutes  n_ingredients
0  127244       60             16
1   23891       25              7
2   94746       10              6
3   67660        5              6
4  157911       60             14

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [11]:
print("Среднее время: ", time.mean())
print("Минимальное время: ", time.min())
print("Максимальное время: ", time.max())
print("Медиана для времени: ", np.median(time), "\n")

Среднее время:  21601.00169
Минимальное время:  0
Максимальное время:  2147483647
Медиана для времени:  40.0 



In [12]:
print("Среднее количество ингредиентов: ", ingredients.mean())
print("Минимальное количество ингредиентов: ", ingredients.min())
print("Максимальное количество ингредиентов: ", ingredients.max())
print("Медиана для количества ингредиентов: ", np.median(ingredients))

Среднее количество ингредиентов:  9.05528
Минимальное количество ингредиентов:  1
Максимальное количество ингредиентов:  39
Медиана для количества ингредиентов:  9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [13]:
quant = np.quantile(dataset, 0.75, axis=0)
print("Ограничение продолжительности выполнения рецепта со значением квантиля 0,75: ", quant[1])

Ограничение продолжительности выполнения рецепта со значением квантиля 0,75:  65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [14]:
zero = np.count_nonzero(dataset==0, axis=0)
print("Количество рецептов с нулевой продолжительностью: ", zero[1])

Количество рецептов с нулевой продолжительностью:  479


In [15]:
print(dataset[-30:], "\n")
array1 = np.where(dataset != 0, dataset, 1)
print(dataset[-30:])

[[377945     30     14]
 [339060     95      8]
 [189545     60      8]
 [279489     15     12]
 [231807     50      8]
 [  2778      0     11]
 [354788     30      9]
 [145282     50     12]
 [ 21006     45      9]
 [100662    210     10]
 [420725      5      3]
 [220747     75      8]
 [273128     25     17]
 [147074     95     15]
 [382708     25     13]
 [  4747      0      9]
 [351058     40      4]
 [ 44120     17      5]
 [138453     30      7]
 [227056     30      4]
 [ 60756     15      5]
 [ 52088     60      5]
 [128811     15      4]
 [360109     30     10]
 [371794     35      8]
 [ 43407     35      7]
 [287943     85     15]
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]] 

[[377945     30     14]
 [339060     95      8]
 [189545     60      8]
 [279489     15     12]
 [231807     50      8]
 [  2778      0     11]
 [354788     30      9]
 [145282     50     12]
 [ 21006     45      9]
 [100662    210     10]
 [420725      5      3]
 [220747     

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [16]:
unique = np.unique(ids)
print("Количество уникальных рецептов: ", len(unique))

Количество уникальных рецептов:  100000


In [17]:
unique = np.unique(dataset, return_counts = True, axis=0)
print("Количество уникальных рецептов: ", len(unique[0]))

Количество уникальных рецептов:  100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [18]:
unique_ingr = np.unique(ingredients)
print("Количество уникальных ингредиентов: ", len(unique_ingr))
print("Значения уникальных ингредиентов: ", unique_ingr)

Количество уникальных ингредиентов:  37
Значения уникальных ингредиентов:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [19]:
filtering = ingredients[ingredients <= 5]
print(filtering)
print(filtering.size)

[5 3 4 ... 5 4 4]
17262


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [20]:
filtering = dataset[time > 0]
ing_per_min = filtering[:, 2] / filtering[:,1]
print("Max ingredients per minute: ", ing_per_min.max())

Max ingredients per minute:  23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [21]:
copy1 = np.copy(dataset)
# Найдем порядок расположения второго столбца (в порядке возрастания)
index = np.argsort(copy1[:,1])
# Изменим порядок (так, чтобы он был в порядке убывания)
rind = index[::-1]
# Возвращаем матрицу со строками в указанном порядке
copy1 = copy1[rind]
copy1 = copy1[:100]
avg = np.mean(copy1, axis=0)
print("Среднее количество ингредиентов для топ-100 рецептов: ", avg[2])

Среднее количество ингредиентов для топ-100 рецептов:  6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [22]:
copy2 = np.copy(dataset)
np.random.shuffle(copy2)
rows = copy2[:10, :]
print("10 случайных рецептов:\n", rows)

10 случайных рецептов:
 [[204461     40     15]
 [380110     10      7]
 [ 58172     25      7]
 [235338     50      9]
 [394047     26      6]
 [ 52097     25      5]
 [ 85801     21      7]
 [429766     70     11]
 [176550     50      6]
 [ 89516     45     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [23]:
count_all = ingredients.size
count_i = ingredients[ingredients < ingredients.mean()].size
print(count_all)
print(count_i)
print((count_i/count_all) * 100, "%")

100000
58802
58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [24]:
zeros = np.zeros((ids.size, 1), dtype=int)
simple = np.append(dataset, zeros, axis=1)
print(simple)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      0]
 [ 81993    140     14      0]]


In [25]:
a = simple[:, 1] <= 20
b = simple[:,2] <= 5
c = a & b
inv = simple[:,3]
inv[c] = 1;
simple[:,3] = inv
print(simple[:15])

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 [ 67660      5      6      0]
 [157911     60     14      0]
 [152828     40      7      0]
 [ 33941     18      9      0]
 [446597     15      5      1]
 [366174      7      9      0]
 [ 74205     20      7      0]
 [504666     65     20      0]
 [ 81006     12      7      0]
 [280968     85     11      0]
 [204134      5      3      1]
 [ 18593     35      7      0]]


13. Выведите процент "простых" рецептов в датасете

In [26]:
column = simple[:,3]
count_i = column[column == 1].size
percent = (count_i/count_all) * 100
print(percent, "%")

9.552 %
